# Generated by Django 4.1.2 on 2022-10-27 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='department_name',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='first_name',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='last_name',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
