# Generated by Django 4.1.2 on 2022-10-27 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_employee_department_name_employee_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(default=0, max_length=20)),
                ('department_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='department_name',
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(default=0, max_length=15),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(default=0, max_length=15),
        ),
        migrations.AddField(
            model_name='employee',
            name='department_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.department'),
        ),
    ]
