# Generated by Django 4.1.2 on 2022-10-27 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_department_id_employee_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='department',
            new_name='department_id',
        ),
    ]
